#pragma once

#include <cinttypes>

#include "pxl/scancode.h"

namespace pxl {
	enum keycode : uint32_t {
		keycode_unknown = 0,
		keycode_backspace = 8,
		keycode_tab,
		keycode_return = 13,
		keycode_escape = 27,
		keycode_space = 32,
		keycode_exclaim,
		keycode_quotedbl,
		keycode_hash,
		keycode_dollar,
		keycode_percent,
		keycode_ampersand,
		keycode_quote,
		keycode_leftparen,
		keycode_rightparen,
		keycode_asterisk,
		keycode_plus,
		keycode_comma,
		keycode_minus,
		keycode_period,
		keycode_slash,
		keycode_0,
		keycode_1,
		keycode_2,
		keycode_3,
		keycode_4,
		keycode_5,
		keycode_6,
		keycode_7,
		keycode_8,
		keycode_9,
		keycode_colon,
		keycode_semicolon,
		keycode_less,
		keycode_equals,
		keycode_greater,
		keycode_question,
		keycode_at,
		keycode_leftbracket = 91,
		keycode_backslash,
		keycode_rightbracket,
		keycode_caret,
		keycode_underscore,
		keycode_backquote,
		keycode_a,
		keycode_b,
		keycode_c,
		keycode_d,
		keycode_e,
		keycode_f,
		keycode_g,
		keycode_h,
		keycode_i,
		keycode_j,
		keycode_k,
		keycode_l,
		keycode_m,
		keycode_n,
		keycode_o,
		keycode_p,
		keycode_q,
		keycode_r,
		keycode_s,
		keycode_t,
		keycode_u,
		keycode_v,
		keycode_w,
		keycode_x,
		keycode_y,
		keycode_z,
		keycode_delete = 127,
		keycode_capslock = 0x40000039,
		keycode_f1,
		keycode_f2,
		keycode_f3,
		keycode_f4,
		keycode_f5,
		keycode_f6,
		keycode_f7,
		keycode_f8,
		keycode_f9,
		keycode_f10,
		keycode_f11,
		keycode_f12,
		keycode_printscreen,
		keycode_scrolllock,
		keycode_pause,
		keycode_insert,
		keycode_home,
		keycode_pageup,
		keycode_end = 0x4000004D,
		keycode_pagedown,
		keycode_right,
		keycode_left,
		keycode_down,
		keycode_up,
		keycode_numlockclear,
		keycode_kp_divide,
		keycode_kp_multiply,
		keycode_kp_minus,
		keycode_kp_plus,
		keycode_kp_enter,
		keycode_kp_1,
		keycode_kp_2,
		keycode_kp_3,
		keycode_kp_4,
		keycode_kp_5,
		keycode_kp_6,
		keycode_kp_7,
		keycode_kp_8,
		keycode_kp_9,
		keycode_kp_0,
		keycode_kp_period,
		keycode_application = 0x40000065,
		keycode_power,
		keycode_kp_equals,
		keycode_f13,
		keycode_f14,
		keycode_f15,
		keycode_f16,
		keycode_f17,
		keycode_f18,
		keycode_f19,
		keycode_f20,
		keycode_f21,
		keycode_f22,
		keycode_f23,
		keycode_f24,
		keycode_execute,
		keycode_help,
		keycode_menu,
		keycode_select,
		keycode_stop,
		keycode_again,
		keycode_undo,
		keycode_cut,
		keycode_copy,
		keycode_paste,
		keycode_find,
		keycode_mute,
		keycode_volumeup,
		keycode_volumedown,
		keycode_kp_comma = 0x40000085,
		keycode_kp_equalsas400,
		keycode_alterase = 0x40000099,
		keycode_sysreq,
		keycode_cancel,
		keycode_clear,
		keycode_prior,
		keycode_return2,
		keycode_separator,
		keycode_out,
		keycode_oper,
		keycode_clearagain,
		keycode_crsel,
		keycode_exsel,
		keycode_kp_00 = 0x400000B0,
		keycode_kp_000,
		keycode_thousandsseparator,
		keycode_decimalseparator,
		keycode_currencyunit,
		keycode_currencysubunit,
		keycode_kp_leftparen,
		keycode_kp_rightparen,
		keycode_kp_leftbrace,
		keycode_kp_rightbrace,
		keycode_kp_tab,
		keycode_kp_backspace,
		keycode_kp_a,
		keycode_kp_b,
		keycode_kp_c,
		keycode_kp_d,
		keycode_kp_e,
		keycode_kp_f,
		keycode_kp_xor,
		keycode_kp_power,
		keycode_kp_percent,
		keycode_kp_less,
		keycode_kp_greater,
		keycode_kp_ampersand,
		keycode_kp_dblampersand,
		keycode_kp_verticalbar,
		keycode_kp_dblverticalbar,
		keycode_kp_colon,
		keycode_kp_hash,
		keycode_kp_space,
		keycode_kp_at,
		keycode_kp_exclam,
		keycode_kp_memstore,
		keycode_kp_memrecall,
		keycode_kp_memclear,
		keycode_kp_memadd,
		keycode_kp_memsubtract,
		keycode_kp_memmultiply,
		keycode_kp_memdivide,
		keycode_kp_plusminus,
		keycode_kp_clear,
		keycode_kp_clearentry,
		keycode_kp_binary,
		keycode_kp_octal,
		keycode_kp_decimal,
		keycode_kp_hexadecimal,
		keycode_lctrl = 0x400000E0,
		keycode_lshift,
		keycode_lalt,
		keycode_lgui,
		keycode_rctrl,
		keycode_rshift,
		keycode_ralt,
		keycode_rgui,
		keycode_mode = 0x40000101,
		keycode_audionext,
		keycode_audioprev,
		keycode_audiostop,
		keycode_audioplay,
		keycode_audiomute,
		keycode_mediaselect,
		keycode_www,
		keycode_mail,
		keycode_calculator,
		keycode_computer,
		keycode_ac_search,
		keycode_ac_home,
		keycode_ac_back,
		keycode_ac_forward,
		keycode_ac_stop,
		keycode_ac_refresh,
		keycode_ac_bookmarks,
		keycode_brightnessdown,
		keycode_brightnessup,
		keycode_displayswitch,
		keycode_kbdillumtoggle,
		keycode_kbdillumdown,
		keycode_kbdillumup,
		keycode_eject,
		keycode_sleep,
	};

	enum modifier : uint16_t {
		modifier_none = 0x0000,
		modifier_lshift = 0x0001,
		modifier_rshift = 0x0002,
		modifier_lctrl = 0x0040,
		modifier_rctrl = 0x0080,
		modifier_lalt = 0x0100,
		modifier_ralt = 0x0200,
		modifier_lgui = 0x0400,
		modifier_rgui = 0x0800,
		modifier_num = 0x1000,
		modifier_caps = 0x2000,
		modifier_mode = 0x4000,
		modifier_reserved = 0x8000,
		modifier_ctrl = modifier_lctrl | modifier_rctrl,
		modifier_shift = modifier_lshift | modifier_rshift,
		modifier_alt = modifier_lalt | modifier_ralt,
		modifier_gui = modifier_lgui | modifier_rgui,
	};

	enum scancode : uint16_t;
	extern scancode to_scancode(keycode code);
}